/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Model.Patient;
import Model.Symptom;
import Process.ListMedicineCrud;
import Process.ListPatientsCrud;
import Process.ListPeopleCrud;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LucasCorrea
 */
public class DoctorDashboard extends javax.swing.JFrame {

    
    private ListPatientsCrud listPatients = new ListPatientsCrud("Patients");
    private ListMedicineCrud listMedicine = new ListMedicineCrud("Medicines");
    
    /**
     * Creates new form Doctor
     */
    public DoctorDashboard(ListPatientsCrud listPatients) {
        initComponents();
        jButtonAttend.setEnabled(false);
        this.listPatients = listPatients;
        listar(0,false);
    }
    
    
     public void listar(int cod, boolean isPesquisa) {
        DefaultListModel modelList = new DefaultListModel();

        if (isPesquisa) {
            
            Patient patients = listPatients.consultByCode(cod);
            if (patients == null) {
                JOptionPane.showMessageDialog(null, "Imóvel não encontrado");
            } else {
                modelList.addElement(patients.toString());
                
            }
        } else {
            List<Patient> patient = listPatients.getLista();
            for (Patient patient1 : patient) {
                modelList.addElement(patient1.toString());
            }
            
        }
        
        jListPatients.setModel(modelList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPatients = new javax.swing.JList();
        jButtonAttend = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNewAttendance = new javax.swing.JMenu();
        jMenuItemNewPatient = new javax.swing.JMenuItem();
        jButtonMedicine = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consultations");

        jListPatients.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListPatients.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPatientsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListPatients);

        jButtonAttend.setText("Attend Patient");
        jButtonAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendActionPerformed(evt);
            }
        });

        jMenuNewAttendance.setText("File");

        jMenuItemNewPatient.setText("New Patient");
        jMenuItemNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNewPatientActionPerformed(evt);
            }
        });
        jMenuNewAttendance.add(jMenuItemNewPatient);

        jButtonMedicine.setText("New Medicine");
        jButtonMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicineActionPerformed(evt);
            }
        });
        jMenuNewAttendance.add(jButtonMedicine);

        jMenuItem2.setText("New Attendance");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuNewAttendance.add(jMenuItem2);

        jMenuBar1.add(jMenuNewAttendance);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAttend)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonAttend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemNewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewPatientActionPerformed
        // TODO add your handling code here:
        new NewPatient(this.listPatients).setVisible(true);
    }//GEN-LAST:event_jMenuItemNewPatientActionPerformed

    private void jButtonAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendActionPerformed
        // TODO add your handling code here:
        listar(0, false);
    }//GEN-LAST:event_jButtonAttendActionPerformed

    private void jListPatientsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPatientsValueChanged
        // TODO add your handling code here:
        if(jListPatients.isSelectionEmpty()){
            jButtonAttend.setEnabled(false);
        }else{
            jButtonAttend.setEnabled(true);
        }
        
    }//GEN-LAST:event_jListPatientsValueChanged

    private void jButtonMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicineActionPerformed
        try {
            listMedicine.readingMedicines();
        } catch (IOException ex) {
            Logger.getLogger(DoctorDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        new NewMedicine(this.listMedicine).setVisible(true);
    }//GEN-LAST:event_jButtonMedicineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDashboard(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAttend;
    private javax.swing.JMenuItem jButtonMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListPatients;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemNewPatient;
    private javax.swing.JMenu jMenuNewAttendance;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
